### ISSUE TITLE
Maybe this is of use to you?

### ISSUE THREAD

**Issue by James-Sangalli** [airswap/developers#13]
Hi,

I created a smart contract that allows cross chain swapping between Bitcoin and Ethereum on the same key (as both use the same key algo).

Is this something of use to you?

Link: https://github.com/James-Sangalli/learn-solidity-with-examples/tree/master/Finance/bitcoin-to-ethereum-swap

**Comment by grahamperich** [comment]
This is interesting work. However, we would prefer to see a BTC <—> ETH swap methodology gain traction in the greater ethereum community before implementing it on our platform
