### ISSUE TITLE
Add Order server URL as env var

### ISSUE THREAD

**Issue by grandizzy** [airswap/developers#27]
Would be nice to have order server URL possible to be passed as env var to api server - this can be useful when api server and order server are started as Docker images and they can be referenced using container names (see https://github.com/grandizzy/airswap-api-server/blob/master/docker-compose.yml sample which I can contribute here if you guys interested)

I issued PR https://github.com/airswap/developers/pull/26 for adding this option

Thanks

**Comment by perich** [comment]
Thanks, we went ahead and merged this #26
